const elementsData = [
	{ number: 1, symbol: 'H', name: 'Hydrogen', maxBonds: 1, row: 1, col: 1, color: 0xFFFFFF, radius: 0.37, atomicMass: 1.008, electronegativity: 2.20, category: 'diatomic-nonmetal' },
	{ number: 2, symbol: 'He', name: 'Helium', maxBonds: 0, row: 1, col: 18, color: 0xD9FFFF, radius: 0.32, atomicMass: 4.0026, electronegativity: null, category: 'noble-gas' },
	{ number: 3, symbol: 'Li', name: 'Lithium', maxBonds: 1, row: 2, col: 1, color: 0xCC80FF, radius: 1.34, atomicMass: 6.94, electronegativity: 0.98, category: 'alkali-metal' },
	{ number: 4, symbol: 'Be', name: 'Beryllium', maxBonds: 2, row: 2, col: 2, color: 0xC2FF00, radius: 0.90, atomicMass: 9.0122, electronegativity: 1.57, category: 'alkaline-earth-metal' },
	{ number: 5, symbol: 'B', name: 'Boron', maxBonds: 3, row: 2, col: 13, color: 0xFFB5B5, radius: 0.82, atomicMass: 10.81, electronegativity: 2.04, category: 'metalloid' },
	{ number: 6, symbol: 'C', name: 'Carbon', maxBonds: 4, row: 2, col: 14, color: 0x909090, radius: 0.77, atomicMass: 12.011, electronegativity: 2.55, category: 'polyatomic-nonmetal' },
	{ number: 7, symbol: 'N', name: 'Nitrogen', maxBonds: 3, row: 2, col: 15, color: 0x3050F8, radius: 0.75, atomicMass: 14.007, electronegativity: 3.04, category: 'diatomic-nonmetal' },
	{ number: 8, symbol: 'O', name: 'Oxygen', maxBonds: 2, row: 2, col: 16, color: 0xFF0D0D, radius: 0.73, atomicMass: 15.999, electronegativity: 3.44, category: 'diatomic-nonmetal' },
	{ number: 9, symbol: 'F', name: 'Fluorine', maxBonds: 1, row: 2, col: 17, color: 0x90E050, radius: 0.71, atomicMass: 18.998, electronegativity: 3.98, category: 'diatomic-nonmetal' },
	{ number: 10, symbol: 'Ne', name: 'Neon', maxBonds: 0, row: 2, col: 18, color: 0xB3E3F5, radius: 0.69, atomicMass: 20.180, electronegativity: null, category: 'noble-gas' },
	{ number: 11, symbol: 'Na', name: 'Sodium', maxBonds: 1, row: 3, col: 1, color: 0xAB5CF2, radius: 1.54, atomicMass: 22.990, electronegativity: 0.93, category: 'alkali-metal' },
	{ number: 12, symbol: 'Mg', name: 'Magnesium', maxBonds: 2, row: 3, col: 2, color: 0x8AFF00, radius: 1.30, atomicMass: 24.305, electronegativity: 1.31, category: 'alkaline-earth-metal' },
	{ number: 13, symbol: 'Al', name: 'Aluminum', maxBonds: 3, row: 3, col: 13, color: 0xBFA6A6, radius: 1.18, atomicMass: 26.982, electronegativity: 1.61, category: 'post-transition-metal' },
	{ number: 14, symbol: 'Si', name: 'Silicon', maxBonds: 4, row: 3, col: 14, color: 0xF0C8A0, radius: 1.11, atomicMass: 28.085, electronegativity: 1.90, category: 'metalloid' },
	{ number: 15, symbol: 'P', name: 'Phosphorus', maxBonds: 3, row: 3, col: 15, color: 0xFF8000, radius: 1.06, atomicMass: 30.974, electronegativity: 2.19, category: 'polyatomic-nonmetal' },
	{ number: 16, symbol: 'S', name: 'Sulfur', maxBonds: 2, row: 3, col: 16, color: 0xFFFF30, radius: 1.02, atomicMass: 32.06, electronegativity: 2.58, category: 'polyatomic-nonmetal' },
	{ number: 17, symbol: 'Cl', name: 'Chlorine', maxBonds: 1, row: 3, col: 17, color: 0x1FF01F, radius: 0.99, atomicMass: 35.45, electronegativity: 3.16, category: 'diatomic-nonmetal' },
	{ number: 18, symbol: 'Ar', name: 'Argon', maxBonds: 0, row: 3, col: 18, color: 0x80D1F5, radius: 0.97, atomicMass: 39.948, electronegativity: null, category: 'noble-gas' },
	{ number: 19, symbol: 'K', name: 'Potassium', maxBonds: 1, row: 4, col: 1, color: 0x8F40D4, radius: 1.96, atomicMass: 39.098, electronegativity: 0.82, category: 'alkali-metal' },
	{ number: 20, symbol: 'Ca', name: 'Calcium', maxBonds: 2, row: 4, col: 2, color: 0x3DFF00, radius: 1.74, atomicMass: 40.078, electronegativity: 1.00, category: 'alkaline-earth-metal' },
	{ number: 21, symbol: 'Sc', name: 'Scandium', maxBonds: 3, row: 4, col: 3, color: 0xE6E6E6, radius: 1.44, atomicMass: 44.956, electronegativity: 1.36, category: 'transition-metal' },
	{ number: 22, symbol: 'Ti', name: 'Titanium', maxBonds: 4, row: 4, col: 4, color: 0xBFC2C7, radius: 1.36, atomicMass: 47.867, electronegativity: 1.54, category: 'transition-metal' },
	{ number: 23, symbol: 'V', name: 'Vanadium', maxBonds: 5, row: 4, col: 5, color: 0xA6A6AB, radius: 1.25, atomicMass: 50.942, electronegativity: 1.63, category: 'transition-metal' },
	{ number: 24, symbol: 'Cr', name: 'Chromium', maxBonds: 6, row: 4, col: 6, color: 0x8A99C7, radius: 1.27, atomicMass: 51.996, electronegativity: 1.66, category: 'transition-metal' },
	{ number: 25, symbol: 'Mn', name: 'Manganese', maxBonds: 7, row: 4, col: 7, color: 0x9C7AC7, radius: 1.39, atomicMass: 54.938, electronegativity: 1.55, category: 'transition-metal' },
	{ number: 26, symbol: 'Fe', name: 'Iron', maxBonds: 3, row: 4, col: 8, color: 0xE06633, radius: 1.25, atomicMass: 55.845, electronegativity: 1.83, category: 'transition-metal' },
	{ number: 27, symbol: 'Co', name: 'Cobalt', maxBonds: 3, row: 4, col: 9, color: 0xF090A0, radius: 1.26, atomicMass: 58.933, electronegativity: 1.88, category: 'transition-metal' },
	{ number: 28, symbol: 'Ni', name: 'Nickel', maxBonds: 2, row: 4, col: 10, color: 0x50D050, radius: 1.21, atomicMass: 58.693, electronegativity: 1.91, category: 'transition-metal' },
	{ number: 29, symbol: 'Cu', name: 'Copper', maxBonds: 2, row: 4, col: 11, color: 0xC88033, radius: 1.38, atomicMass: 63.546, electronegativity: 1.90, category: 'transition-metal' },
	{ number: 30, symbol: 'Zn', name: 'Zinc', maxBonds: 2, row: 4, col: 12, color: 0x7D80B0, radius: 1.31, atomicMass: 65.38, electronegativity: 1.65, category: 'transition-metal' },
	{ number: 31, symbol: 'Ga', name: 'Gallium', maxBonds: 3, row: 4, col: 13, color: 0xC28F8F, radius: 1.26, atomicMass: 69.723, electronegativity: 1.81, category: 'post-transition-metal' },
	{ number: 32, symbol: 'Ge', name: 'Germanium', maxBonds: 4, row: 4, col: 14, color: 0x668F8F, radius: 1.22, atomicMass: 72.63, electronegativity: 2.01, category: 'metalloid' },
	{ number: 33, symbol: 'As', name: 'Arsenic', maxBonds: 3, row: 4, col: 15, color: 0xBD80E3, radius: 1.19, atomicMass: 74.922, electronegativity: 2.18, category: 'metalloid' },
	{ number: 34, symbol: 'Se', name: 'Selenium', maxBonds: 2, row: 4, col: 16, color: 0xFFA100, radius: 1.16, atomicMass: 78.971, electronegativity: 2.55, category: 'polyatomic-nonmetal' },
	{ number: 35, symbol: 'Br', name: 'Bromine', maxBonds: 1, row: 4, col: 17, color: 0xA62929, radius: 1.14, atomicMass: 79.904, electronegativity: 2.96, category: 'diatomic-nonmetal' },
	{ number: 36, symbol: 'Kr', name: 'Krypton', maxBonds: 0, row: 4, col: 18, color: 0x5CB8D1, radius: 1.10, atomicMass: 83.798, electronegativity: 3.00, category: 'noble-gas' },
	{ number: 37, symbol: 'Rb', name: 'Rubidium', maxBonds: 1, row: 5, col: 1, color: 0x702EB0, radius: 2.11, atomicMass: 85.468, electronegativity: 0.82, category: 'alkali-metal' },
	{ number: 38, symbol: 'Sr', name: 'Strontium', maxBonds: 2, row: 5, col: 2, color: 0x00FF00, radius: 1.92, atomicMass: 87.62, electronegativity: 0.95, category: 'alkaline-earth-metal' },
	{ number: 39, symbol: 'Y', name: 'Yttrium', maxBonds: 3, row: 5, col: 3, color: 0x94FFFF, radius: 1.62, atomicMass: 88.906, electronegativity: 1.22, category: 'transition-metal' },
	{ number: 40, symbol: 'Zr', name: 'Zirconium', maxBonds: 4, row: 5, col: 4, color: 0x94E0E0, radius: 1.48, atomicMass: 91.224, electronegativity: 1.33, category: 'transition-metal' },
	{ number: 41, symbol: 'Nb', name: 'Niobium', maxBonds: 5, row: 5, col: 5, color: 0x73C2C9, radius: 1.37, atomicMass: 92.906, electronegativity: 1.6, category: 'transition-metal' },
	{ number: 42, symbol: 'Mo', name: 'Molybdenum', maxBonds: 6, row: 5, col: 6, color: 0x54B5B5, radius: 1.45, atomicMass: 95.96, electronegativity: 2.16, category: 'transition-metal' },
	{ number: 43, symbol: 'Tc', name: 'Technetium', maxBonds: 7, row: 5, col: 7, color: 0x3B9E9E, radius: 1.56, atomicMass: 98, electronegativity: 1.9, category: 'transition-metal' },
	{ number: 44, symbol: 'Ru', name: 'Ruthenium', maxBonds: 4, row: 5, col: 8, color: 0x248F8F, radius: 1.26, atomicMass: 101.07, electronegativity: 2.2, category: 'transition-metal' },
	{ number: 45, symbol: 'Rh', name: 'Rhodium', maxBonds: 4, row: 5, col: 9, color: 0x0A7D8C, radius: 1.35, atomicMass: 102.91, electronegativity: 2.28, category: 'transition-metal' },
	{ number: 46, symbol: 'Pd', name: 'Palladium', maxBonds: 2, row: 5, col: 10, color: 0x006985, radius: 1.31, atomicMass: 106.42, electronegativity: 2.20, category: 'transition-metal' },
	{ number: 47, symbol: 'Ag', name: 'Silver', maxBonds: 1, row: 5, col: 11, color: 0xC0C0C0, radius: 1.53, atomicMass: 107.87, electronegativity: 1.93, category: 'transition-metal' },
	{ number: 48, symbol: 'Cd', name: 'Cadmium', maxBonds: 2, row: 5, col: 12, color: 0xFFD98F, radius: 1.48, atomicMass: 112.41, electronegativity: 1.69, category: 'transition-metal' },
	{ number: 49, symbol: 'In', name: 'Indium', maxBonds: 3, row: 5, col: 13, color: 0xA67573, radius: 1.44, atomicMass: 114.82, electronegativity: 1.78, category: 'post-transition-metal' },
	{ number: 50, symbol: 'Sn', name: 'Tin', maxBonds: 4, row: 5, col: 14, color: 0x668080, radius: 1.41, atomicMass: 118.71, electronegativity: 1.96, category: 'post-transition-metal' },
	{ number: 51, symbol: 'Sb', name: 'Antimony', maxBonds: 3, row: 5, col: 15, color: 0x9E63B5, radius: 1.38, atomicMass: 121.76, electronegativity: 2.05, category: 'metalloid' },
	{ number: 52, symbol: 'Te', name: 'Tellurium', maxBonds: 2, row: 5, col: 16, color: 0xD47A00, radius: 1.35, atomicMass: 127.60, electronegativity: 2.1, category: 'metalloid' },
	{ number: 53, symbol: 'I', name: 'Iodine', maxBonds: 1, row: 5, col: 17, color: 0x940094, radius: 1.33, atomicMass: 126.90, electronegativity: 2.66, category: 'diatomic-nonmetal' },
	{ number: 54, symbol: 'Xe', name: 'Xenon', maxBonds: 0, row: 5, col: 18, color: 0x429EB0, radius: 1.30, atomicMass: 131.29, electronegativity: 2.6, category: 'noble-gas' },
	{ number: 55, symbol: 'Cs', name: 'Caesium', maxBonds: 1, row: 6, col: 1, color: 0x57178F, radius: 2.25, atomicMass: 132.91, electronegativity: 0.79, category: 'alkali-metal' },
	{ number: 56, symbol: 'Ba', name: 'Barium', maxBonds: 2, row: 6, col: 2, color: 0x00C900, radius: 1.98, atomicMass: 137.33, electronegativity: 0.89, category: 'alkaline-earth-metal' },
	{ number: 72, symbol: 'Hf', name: 'Hafnium', maxBonds: 4, row: 6, col: 4, color: 0x4DC2FF, radius: 1.50, atomicMass: 178.49, electronegativity: 1.3, category: 'transition-metal' },
	{ number: 73, symbol: 'Ta', name: 'Tantalum', maxBonds: 5, row: 6, col: 5, color: 0x4DA6FF, radius: 1.38, atomicMass: 180.95, electronegativity: 1.5, category: 'transition-metal' },
	{ number: 74, symbol: 'W', name: 'Tungsten', maxBonds: 6, row: 6, col: 6, color: 0x2194D6, radius: 1.46, atomicMass: 183.84, electronegativity: 2.36, category: 'transition-metal' },
	{ number: 75, symbol: 'Re', name: 'Rhenium', maxBonds: 7, row: 6, col: 7, color: 0x267DAB, radius: 1.59, atomicMass: 186.21, electronegativity: 1.9, category: 'transition-metal' },
	{ number: 76, symbol: 'Os', name: 'Osmium', maxBonds: 8, row: 6, col: 8, color: 0x266696, radius: 1.28, atomicMass: 190.23, electronegativity: 2.2, category: 'transition-metal' },
	{ number: 77, symbol: 'Ir', name: 'Iridium', maxBonds: 4, row: 6, col: 9, color: 0x175487, radius: 1.37, atomicMass: 192.22, electronegativity: 2.20, category: 'transition-metal' },
	{ number: 78, symbol: 'Pt', name: 'Platinum', maxBonds: 4, row: 6, col: 10, color: 0xD0D0E0, radius: 1.28, atomicMass: 195.08, electronegativity: 2.28, category: 'transition-metal' },
	{ number: 79, symbol: 'Au', name: 'Gold', maxBonds: 3, row: 6, col: 11, color: 0xFFD123, radius: 1.44, atomicMass: 196.97, electronegativity: 2.54, category: 'transition-metal' },
	{ number: 80, symbol: 'Hg', name: 'Mercury', maxBonds: 2, row: 6, col: 12, color: 0xB8B8D0, radius: 1.49, atomicMass: 200.59, electronegativity: 2.00, category: 'transition-metal' },
	{ number: 81, symbol: 'Tl', name: 'Thallium', maxBonds: 1, row: 6, col: 13, color: 0xA6544D, radius: 1.48, atomicMass: 204.38, electronegativity: 1.62, category: 'post-transition-metal' },
	{ number: 82, symbol: 'Pb', name: 'Lead', maxBonds: 2, row: 6, col: 14, color: 0x575961, radius: 1.47, atomicMass: 207.2, electronegativity: 1.87, category: 'post-transition-metal' },
	{ number: 83, symbol: 'Bi', name: 'Bismuth', maxBonds: 3, row: 6, col: 15, color: 0x9E4FB5, radius: 1.46, atomicMass: 208.98, electronegativity: 2.02, category: 'post-transition-metal' },
	{ number: 84, symbol: 'Po', name: 'Polonium', maxBonds: 2, row: 6, col: 16, color: 0xAB5C00, radius: 1.40, atomicMass: 209, electronegativity: 2.0, category: 'post-transition-metal' },
	{ number: 85, symbol: 'At', name: 'Astatine', maxBonds: 1, row: 6, col: 17, color: 0x754F45, radius: 1.50, atomicMass: 210, electronegativity: 2.2, category: 'metalloid' },
	{ number: 86, symbol: 'Rn', name: 'Radon', maxBonds: 0, row: 6, col: 18, color: 0x428296, radius: 1.45, atomicMass: 222, electronegativity: 2.2, category: 'noble-gas' },
	{ number: 87, symbol: 'Fr', name: 'Francium', maxBonds: 1, row: 7, col: 1, color: 0x420066, radius: 2.23, atomicMass: 223, electronegativity: 0.7, category: 'alkali-metal' },
	{ number: 88, symbol: 'Ra', name: 'Radium', maxBonds: 2, row: 7, col: 2, color: 0x007D00, radius: 2.01, atomicMass: 226, electronegativity: 0.9, category: 'alkaline-earth-metal' },
	{ number: 104, symbol: 'Rf', name: 'Rutherfordium', maxBonds: 4, row: 7, col: 4, color: 0x003B70, radius: 1.57, atomicMass: 267, electronegativity: null, category: 'transition-metal' },
	{ number: 105, symbol: 'Db', name: 'Dubnium', maxBonds: 5, row: 7, col: 5, color: 0x00448A, radius: 1.49, atomicMass: 270, electronegativity: null, category: 'transition-metal' },
	{ number: 106, symbol: 'Sg', name: 'Seaborgium', maxBonds: 6, row: 7, col: 6, color: 0x004F9E, radius: 1.43, atomicMass: 271, electronegativity: null, category: 'transition-metal' },
	{ number: 107, symbol: 'Bh', name: 'Bohrium', maxBonds: 7, row: 7, col: 7, color: 0x0059B3, radius: 1.41, atomicMass: 270, electronegativity: null, category: 'transition-metal' },
	{ number: 108, symbol: 'Hs', name: 'Hassium', maxBonds: 8, row: 7, col: 8, color: 0x0063C7, radius: 1.34, atomicMass: 277, electronegativity: null, category: 'transition-metal' },
	{ number: 109, symbol: 'Mt', name: 'Meitnerium', maxBonds: 4, row: 7, col: 9, color: 0x006EDC, radius: 1.29, atomicMass: 278, electronegativity: null, category: 'unknown' },
	{ number: 110, symbol: 'Ds', name: 'Darmstadtium', maxBonds: 4, row: 7, col: 10, color: 0x0078F0, radius: 1.28, atomicMass: 281, electronegativity: null, category: 'unknown' },
	{ number: 111, symbol: 'Rg', name: 'Roentgenium', maxBonds: 3, row: 7, col: 11, color: 0x0080FF, radius: 1.21, atomicMass: 282, electronegativity: null, category: 'unknown' },
	{ number: 112, symbol: 'Cn', name: 'Copernicium', maxBonds: 2, row: 7, col: 12, color: 0x0880FF, radius: 1.22, atomicMass: 285, electronegativity: null, category: 'transition-metal' },
	{ number: 113, symbol: 'Nh', name: 'Nihonium', maxBonds: 1, row: 7, col: 13, color: 0x1080FF, radius: 1.36, atomicMass: 286, electronegativity: null, category: 'unknown' },
	{ number: 114, symbol: 'Fl', name: 'Flerovium', maxBonds: 2, row: 7, col: 14, color: 0x1880FF, radius: 1.43, atomicMass: 289, electronegativity: null, category: 'post-transition-metal' },
	{ number: 115, symbol: 'Mc', name: 'Moscovium', maxBonds: 3, row: 7, col: 15, color: 0x2080FF, radius: 1.62, atomicMass: 290, electronegativity: null, category: 'unknown' },
	{ number: 116, symbol: 'Lv', name: 'Livermorium', maxBonds: 2, row: 7, col: 16, color: 0x2880FF, radius: 1.75, atomicMass: 293, electronegativity: null, category: 'unknown' },
	{ number: 117, symbol: 'Ts', name: 'Tennessine', maxBonds: 1, row: 7, col: 17, color: 0x3080FF, radius: 1.65, atomicMass: 294, electronegativity: null, category: 'unknown' },
	{ number: 118, symbol: 'Og', name: 'Oganesson', maxBonds: 0, row: 7, col: 18, color: 0x3880FF, radius: 1.57, atomicMass: 294, electronegativity: null, category: 'unknown' }
];

const ELECTRON_GEOMETRIES = {
	2: [
		new THREE.Vector3(1, 0, 0),
		new THREE.Vector3(-1, 0, 0)
	],
	3: [
		new THREE.Vector3(1, 0, 0),
		new THREE.Vector3(-0.5, Math.sqrt(3) / 2, 0),
		new THREE.Vector3(-0.5, -Math.sqrt(3) / 2, 0)
	],
	4: [
		new THREE.Vector3(1, 1, 1).normalize(),
		new THREE.Vector3(-1, -1, 1).normalize(),
		new THREE.Vector3(-1, 1, -1).normalize(),
		new THREE.Vector3(1, -1, -1).normalize()
	],
	5: [
		new THREE.Vector3(0, 0, 1),
		new THREE.Vector3(0, 0, -1),
		new THREE.Vector3(1, 0, 0),
		new THREE.Vector3(-0.5, Math.sqrt(3) / 2, 0),
		new THREE.Vector3(-0.5, -Math.sqrt(3) / 2, 0)
	],
	6: [
		new THREE.Vector3(0, 0, 1),
		new THREE.Vector3(0, 0, -1),
		new THREE.Vector3(1, 0, 0),
		new THREE.Vector3(-1, 0, 0),
		new THREE.Vector3(0, 1, 0),
		new THREE.Vector3(0, -1, 0)
	],
	7: [
		new THREE.Vector3(0, 0, 1),
		new THREE.Vector3(0, 0, -1),
		new THREE.Vector3(1, 0, 0),
		new THREE.Vector3(Math.cos(2 * Math.PI / 5), Math.sin(2 * Math.PI / 5), 0),
		new THREE.Vector3(Math.cos(4 * Math.PI / 5), Math.sin(4 * Math.PI / 5), 0),
		new THREE.Vector3(Math.cos(6 * Math.PI / 5), Math.sin(6 * Math.PI / 5), 0),
		new THREE.Vector3(Math.cos(8 * Math.PI / 5), Math.sin(8 * Math.PI / 5), 0)
	],
	8: [
		new THREE.Vector3(1, 0, 1 / Math.sqrt(2)).normalize(),
		new THREE.Vector3(-1, 0, 1 / Math.sqrt(2)).normalize(),
		new THREE.Vector3(0, 1, 1 / Math.sqrt(2)).normalize(),
		new THREE.Vector3(0, -1, 1 / Math.sqrt(2)).normalize(),
		new THREE.Vector3(1 / Math.sqrt(2), 1 / Math.sqrt(2), -1 / Math.sqrt(2)).normalize(),
		new THREE.Vector3(-1 / Math.sqrt(2), 1 / Math.sqrt(2), -1 / Math.sqrt(2)).normalize(),
		new THREE.Vector3(1 / Math.sqrt(2), -1 / Math.sqrt(2), -1 / Math.sqrt(2)).normalize(),
		new THREE.Vector3(-1 / Math.sqrt(2), -1 / Math.sqrt(2), -1 / Math.sqrt(2)).normalize()
	]
};

const CHEMICAL_DATA = {
	GREEK_PREFIXES: {
		1: '', 2: 'di', 3: 'tri', 4: 'tetra', 5: 'penta', 6: 'hexa', 7: 'hepta', 8: 'octa', 9: 'nona', 10: 'deca',
		11: 'undeca', 12: 'dodeca', 13: 'trideca', 14: 'tetradeca', 15: 'pentadeca', 16: 'hexadeca', 17: 'heptadeca', 18: 'octadeca', 19: 'nonadeca',
		20: 'icosa', 21: 'henicosa', 22: 'docosa', 23: 'tricosa', 24: 'tetracosa', 25: 'pentacosa', 26: 'hexacosa', 27: 'heptacosa', 28: 'octacosa', 29: 'nonacosa',
		30: 'triaconta', 31: 'hentriaconta', 32: 'dotriaconta', 40: 'tetraconta', 50: 'pentaconta', 60: 'hexaconta', 70: 'heptaconta', 80: 'octaconta', 90: 'nonaconta', 100: 'hecta'
	},
	ORGANIC_PREFIXES: {
		1: 'meth', 2: 'eth', 3: 'prop', 4: 'but', 5: 'pent', 6: 'hex', 7: 'hept', 8: 'oct', 9: 'non', 10: 'dec',
		11: 'undec', 12: 'dodec', 13: 'tridec', 14: 'tetradec', 15: 'pentadec', 16: 'hexadec', 17: 'heptadec', 18: 'octadec', 19: 'nonadec',
		20: 'icos', 21: 'henicos', 22: 'docos', 23: 'tricos', 24: 'tetracos', 25: 'pentacos', 26: 'hexacos', 27: 'heptacos', 28: 'octacos', 29: 'nonacos',
		30: 'triacont', 31: 'hentriacont', 40: 'tetracont', 50: 'pentacont', 60: 'hexacont', 70: 'heptacont', 80: 'octacont', 90: 'nonacont', 100: 'hect'
	},
	ELEMENT_ROOTS: {
		'O': 'ox', 'H': 'hydr', 'C': 'carb', 'N': 'nitr', 'P': 'phosph', 'S': 'sulf', 'F': 'fluor', 'Cl': 'chlor',
		'Br': 'brom', 'I': 'iod', 'Se': 'selen', 'As': 'arsen', 'Te': 'tellur', 'B': 'bor', 'Si': 'silic', 'Sb': 'stib',
		'At': 'astat', 'Fe': 'ferr', 'Cu': 'cupr', 'Au': 'aur', 'Ag': 'argent', 'Pb': 'plumb', 'Sn': 'stann', 'Hg': 'mercur',
		'Mn': 'mangan', 'Cr': 'chrom', 'Mo': 'molybd', 'W': 'tungst', 'V': 'vanad', 'Ti': 'titan', 'Zr': 'zircon',
		'Al': 'alumin', 'Ga': 'gall', 'Zn': 'zinc', 'Ni': 'nickel', 'Co': 'cobalt', 'Pt': 'platin', 'Pd': 'pallad',
		'Ir': 'irid', 'Os': 'osm', 'Ru': 'ruthen', 'Rh': 'rhod', 'Re': 'rhen', 'Tc': 'technet', 'Ge': 'german', 'Po': 'polon'
	},
	COMMON_OXIDATION_STATES: {
		'Fe': [3, 2], 'Cu': [2, 1], 'Hg': [2, 1], 'Sn': [4, 2], 'Pb': [4, 2], 'Co': [3, 2], 'Ni': [2, 3], 'Au': [3, 1],
		'Mn': [2, 3, 4, 6, 7], 'Cr': [3, 6, 2], 'V': [5, 4, 3, 2], 'Ti': [4, 3, 2], 'Pt': [4, 2], 'Pd': [4, 2], 'Ag': [1, 2],
		'Zn': [2], 'Cd': [2], 'W': [6, 5, 4, 3, 2], 'Mo': [6, 5, 4, 3, 2, 0], 'Re': [7, 6, 4, 2, -1], 'Tc': [7, 6, 4],
		'Ru': [2, 3, 4, 6, 8], 'Os': [2, 3, 4, 6, 8], 'Rh': [1, 2, 3, 4, 6], 'Ir': [1, 2, 3, 4, 6], 'Nb': [5, 4, 3],
		'Ta': [5, 4], 'Zr': [4, 3, 2], 'Sc': [3], 'Y': [3], 'La': [3], 'Al': [3], 'Ga': [3, 1], 'In': [3, 1],
		'Tl': [3, 1], 'Ge': [4, 2], 'As': [5, 3, -3], 'Sb': [5, 3, -3], 'Bi': [5, 3], 'Po': [6, 4, 2], 'S': [-2, 0, 2, 4, 6],
		'N': [-3, -2, -1, 0, 1, 2, 3, 4, 5], 'P': [-3, 1, 3, 4, 5], 'Cl': [-1, 1, 3, 5, 7], 'Br': [-1, 1, 3, 5, 7], 'I': [-1, 1, 3, 5, 7]
	},
	ROMAN_NUMERALS: {
		1: 'I', 2: 'II', 3: 'III', 4: 'IV', 5: 'V', 6: 'VI', 7: 'VII', 8: 'VIII', 9: 'IX', 10: 'X',
		11: 'XI', 12: 'XII', 13: 'XIII', 14: 'XIV', 15: 'XV', 16: 'XVI', 17: 'XVII', 18: 'XVIII', 19: 'XIX', 20: 'XX'
	}
};

const KNOWN_COMPOUNDS = {
	'H2O': 'Water', 'H2O2': 'Hydrogen Peroxide', 'O3': 'Ozone', 'D2O': 'Heavy Water',
	'CO2': 'Carbon Dioxide', 'CO': 'Carbon Monoxide', 'CS2': 'Carbon Disulfide', 'COS': 'Carbonyl Sulfide',
	'NH3': 'Ammonia', 'N2H4': 'Hydrazine', 'PH3': 'Phosphine', 'AsH3': 'Arsine', 'SbH3': 'Stibine', 'BiH3': 'Bismuthine', 'B2H6': 'Diborane',
	'NO': 'Nitric Oxide', 'NO2': 'Nitrogen Dioxide', 'N2O': 'Nitrous Oxide', 'N2O3': 'Dinitrogen Trioxide', 'N2O4': 'Dinitrogen Tetroxide', 'N2O5': 'Dinitrogen Pentoxide',
	'SO2': 'Sulfur Dioxide', 'SO3': 'Sulfur Trioxide', 'H2S': 'Hydrogen Sulfide', 'SF6': 'Sulfur Hexafluoride', 'SOCl2': 'Thionyl Chloride', 'SO2Cl2': 'Sulfuryl Chloride',
	'SiO2': 'Silicon Dioxide', 'SiH4': 'Silane', 'Si2H6': 'Disilane', 'SiC': 'Silicon Carbide',
	'HCl': 'Hydrogen Chloride', 'HF': 'Hydrogen Fluoride', 'HBr': 'Hydrogen Bromide', 'HI': 'Hydrogen Iodide', 'HCN': 'Hydrogen Cyanide', 'HOCN': 'Isocyanic Acid', 'HNCO': 'Cyanic Acid',
	'H2SO4': 'Sulfuric Acid', 'HNO3': 'Nitric Acid', 'H3PO4': 'Phosphoric Acid', 'H2CO3': 'Carbonic Acid', 'HClO4': 'Perchloric Acid', 'HClO3': 'Chloric Acid', 'HIO3': 'Iodic Acid',
	'H3PO3': 'Phosphorous Acid', 'H3BO3': 'Boric Acid', 'H2SO3': 'Sulfurous Acid', 'H2CrO4': 'Chromic Acid', 'HMnO4': 'Permanganic Acid',
	'NaOH': 'Sodium Hydroxide', 'KOH': 'Potassium Hydroxide', 'Ca(OH)2': 'Calcium Hydroxide', 'Mg(OH)2': 'Magnesium Hydroxide', 'Al(OH)3': 'Aluminum Hydroxide',
	'NaCl': 'Sodium Chloride', 'KCl': 'Potassium Chloride', 'CaCl2': 'Calcium Chloride', 'MgCl2': 'Magnesium Chloride', 'FeCl3': 'Iron(III) Chloride',
	'CaCO3': 'Calcium Carbonate', 'NaHCO3': 'Sodium Bicarbonate', 'Na2CO3': 'Sodium Carbonate', 'K2CO3': 'Potassium Carbonate',
	'NaNO3': 'Sodium Nitrate', 'KNO3': 'Potassium Nitrate', 'NH4Cl': 'Ammonium Chloride', 'Na2SO4': 'Sodium Sulfate', 'CuSO4': 'Copper(II) Sulfate',
	'CH4': 'Methane', 'C2H6': 'Ethane', 'C3H8': 'Propane', 'C4H10': 'Butane', 'C5H12': 'Pentane', 'C6H14': 'Hexane', 'C7H16': 'Heptane', 'C8H18': 'Octane', 'C9H20': 'Nonane', 'C10H22': 'Decane',
	'C2H4': 'Ethene', 'C3H6': 'Propene', 'C4H8': 'Butene', 'C5H10': 'Pentene', 'C6H12': 'Hexene',
	'C2H2': 'Ethyne', 'C3H4': 'Propyne', 'C4H6': 'Butyne', 'C5H8': 'Pentyne', 'C6H10': 'Hexyne',
	'C6H6': 'Benzene', 'C7H8': 'Toluene', 'C8H10': 'Xylene', 'C6H12': 'Cyclohexane', 'C10H8': 'Naphthalene', 'C14H10': 'Anthracene',
	'CH2O': 'Formaldehyde', 'CH4O': 'Methanol', 'C2H4O': 'Acetaldehyde', 'C2H4O2': 'Acetic Acid', 'C2H6O': 'Ethanol',
	'C3H6O': 'Acetone', 'C3H8O': 'Propanol', 'C4H8O': 'Butanone', 'C4H10O': 'Butanol',
	'HCOOH': 'Formic Acid', 'CH3COOH': 'Acetic Acid', 'CH3CH2COOH': 'Propanoic Acid', 'CH3COOCH3': 'Methyl Acetate',
	'CH3OCH3': 'Dimethyl Ether', 'CH3CH2OCH2CH3': 'Diethyl Ether',
	'CH3NH2': 'Methylamine', 'C2H5NH2': 'Ethylamine', 'C6H5NH2': 'Aniline',
	'CH2Cl2': 'Dichloromethane', 'CHCl3': 'Chloroform', 'CCl4': 'Carbon Tetrachloride',
	'C6H12O6': 'Glucose', 'C12H22O11': 'Sucrose', 'C2H5SH': 'Ethanethiol', 'C6H5OH': 'Phenol',
	'CH3COONa': 'Sodium Acetate', 'C6H5COOH': 'Benzoic Acid', 'C6H5COONa': 'Sodium Benzoate',
	'C5H5N': 'Pyridine', 'C4H4O': 'Furan', 'C4H4S': 'Thiophene', 'C4H5N': 'Pyrrole', 'DNA': 'Deoxyribonucleic Acid Segment'
};

const POLYATOMIC_IONS = {
	'H3O': { name: 'hydronium', charge: 1 }, 'NH4': { name: 'ammonium', charge: 1 },
	'CH3COO': { name: 'acetate', charge: -1 }, 'C2H3O2': { name: 'acetate', charge: -1 },
	'CN': { name: 'cyanide', charge: -1 }, 'OCN': { name: 'cyanate', charge: -1 }, 'SCN': { name: 'thiocyanate', charge: -1 },
	'CO3': { name: 'carbonate', charge: -2 }, 'HCO3': { name: 'bicarbonate', charge: -1 },
	'C2O4': { name: 'oxalate', charge: -2 }, 'HC2O4': { name: 'bioxalate', charge: -1 },
	'ClO': { name: 'hypochlorite', charge: -1 }, 'ClO2': { name: 'chlorite', charge: -1 },
	'ClO3': { name: 'chlorate', charge: -1 }, 'ClO4': { name: 'perchlorate', charge: -1 },
	'BrO': { name: 'hypobromite', charge: -1 }, 'BrO2': { name: 'bromite', charge: -1 },
	'BrO3': { name: 'bromate', charge: -1 }, 'BrO4': { name: 'perbromate', charge: -1 },
	'IO': { name: 'hypoiodite', charge: -1 }, 'IO2': { name: 'iodite', charge: -1 },
	'IO3': { name: 'iodate', charge: -1 }, 'IO4': { name: 'periodate', charge: -1 }, 'H4IO6': { name: 'periodate', charge: -1 },
	'CrO4': { name: 'chromate', charge: -2 }, 'Cr2O7': { name: 'dichromate', charge: -2 },
	'MnO4': { name: 'permanganate', charge: -1 }, 'MnO4-2': { name: 'manganate', charge: -2 },
	'NO2': { name: 'nitrite', charge: -1 }, 'NO3': { name: 'nitrate', charge: -1 },
	'OH': { name: 'hydroxide', charge: -1 }, 'O2': { name: 'peroxide', charge: -2 },
	'PO3': { name: 'phosphite', charge: -3 }, 'PO4': { name: 'phosphate', charge: -3 },
	'HPO4': { name: 'hydrogen phosphate', charge: -2 }, 'H2PO4': { name: 'dihydrogen phosphate', charge: -1 },
	'S2O3': { name: 'thiosulfate', charge: -2 }, 'S2O8': { name: 'peroxydisulfate', charge: -2 },
	'SO3': { name: 'sulfite', charge: -2 }, 'SO4': { name: 'sulfate', charge: -2 },
	'HSO3': { name: 'bisulfite', charge: -1 }, 'HSO4': { name: 'bisulfate', charge: -1 },
	'S2O7': { name: 'disulfate', charge: -2 }, 'S4O6': { name: 'tetrathionate', charge: -2 },
	'CNO': { name: 'cyanate', charge: -1 }, 'NCO': { name: 'isocyanato', charge: -1 },
	'SiO3': { name: 'silicate', charge: -2 }, 'BO3': { name: 'borate', charge: -3 }, 'B4O7': { name: 'tetraborate', charge: -2 },
	'AsO3': { name: 'arsenite', charge: -3 }, 'AsO4': { name: 'arsenate', charge: -3 },
	'SeO3': { name: 'selenite', charge: -2 }, 'SeO4': { name: 'selenate', charge: -2 },
	'TeO3': { name: 'tellurite', charge: -2 }, 'TeO4': { name: 'tellurate', charge: -2 },
	'IO5': { name: 'mesoperiodate', charge: -3 }, 'H2VO4': { name: 'vanadate', charge: -1 }, 'VO3': { name: 'metavanadate', charge: -1 },
	'MoO4': { name: 'molybdate', charge: -2 }, 'WO4': { name: 'tungstate', charge: -2 },
	'RuO4': { name: 'ruthenate', charge: -2 }, 'OsO4': { name: 'osmate', charge: -2 },
	'HCOO': { name: 'formate', charge: -1 }, 'C6H5COO': { name: 'benzoate', charge: -1 },
	'Fe(CN)6': { name: 'hexacyanoferrate(II)', charge: -4 }, 'Fe(CN)6-3': { name: 'hexacyanoferrate(III)', charge: -3 }
};